site_name: blog
site_description: why not
site_url: https://blog.ryanatkins.dev
repo_url: https://github.com/ryan-atkins/blog

theme:
  name: material
  palette:
    scheme: dracula
    primary: deep purple
    accent: deep purple
  features:
    - navigation.indexes
    - navigation.sections

plugins:
  - meta
  - search
  - blog:
      blog_dir: .
      blog_toc: true
  - tags
  - mkdocs_pymdownx_material_extras

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ryan-atkins

markdown_extensions:
  - attr_list
