name: mkdocs
description: Deploy mkdocs to GitHub Pages
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: configure git credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: install uv
        uses: astral-sh/setup-uv@v5
        with:
          # install a specific version of uv.
          version: "0.7.3"
      - uses: actions/setup-python@v5
      - name: restore uv cache
        uses: actions/cache@v4
        with:
          path: /tmp/.uv-cache
          key: uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
          restore-keys: |
            uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
            uv-${{ runner.os }}
      - name: install the project
        run: uv sync --locked --all-extras --dev
      - run: uv mkdocs gh-deploy --force
        env:
          PYTHONPATH: '.'
      - name: minimize uv cache
        run: uv cache prune --ci
